version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mathbesedina
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'

  backend:
    # todo: создать скрипт для миграции
    build: .
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - db


volumes:
  postgres_data:
